#!/bin/bash

DOCKER_IMAGE=chick-p/textlint-precommit
DOCKER_IMAGE_VERSION=0.1.1
DOCKER_IMANE_NAME="$DOCKER_IMAGE":"$DOCKER_IMAGE_VERSION"

# shellcheck source=/dev/null
source "$(dirname "${0}")"/_local-hook-exec

FILES="$(git diff --cached --name-only --diff-filter=ACMR "*.md")"
[ -z "$FILES" ] && exit 0

echo "===> Check by textlint"

if [ -z "$(docker images -q "$DOCKER_IMANE_NAME")" ]; then
  echo "Docker image not found. Build it."
  docker build --force-rm=true -t "$DOCKER_IMANE_NAME" .
fi

PWD=$(pwd)
RESULT="$(echo "$FILES" | xargs docker run -v "$PWD":"$PWD" -w "$PWD" --rm $DOCKER_IMANE_NAME textlint)"
RET=$?
echo "$RESULT"

if [ -z "$RESULT" ]; then
  exit 0
fi

if [ $RET -ne 0 ]; then
  echo "textlint failed. Please fix the errors and try again."
  exit 1
fi

exec < /dev/tty
echo "Do you want to commit? [y/N]"
read -r ANSWER
if [ "$ANSWER" != "y" ]; then
  echo "Cancel commit."
  exit 1
fi
