name: hadolint

on:
  push:
    branches:
      - "main"
  pull_request:
    paths:
      - "Dockerfile"

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: hadolint/hadolint-action@v3.2.0
        with:
          dockerfile: Dockerfile
